Add new `check_private_items` config
rust-lang/rust-clippy pull request #11842
Opened 2023-11-19 14:56 UTC by GuillaumeGomez

Fixes https://github.com/rust-lang/rust-clippy/issues/11742.

It adds a new configuration which allows for `MISSING_SAFETY_DOC`, `UNNECESSARY_SAFETY_DOC`, `MISSING_PANICS_DOC` and `MISSING_ERRORS_DOC` lints to run on private items.

r? @blyxyas

2023-11-19 15:55 UTC, xFrednet commented
If this config is specific to doc lints it might be good to include that in the config name. If it's intended as a general setting, then the name should be fine :)

2023-11-19 21:36 UTC, blyxyas requested changes
Meow Meow
Currently blocked by #11801

2023-11-19 21:36 UTC, blyxyas commented on clippy_config/src/conf.rs
> +    (check_private_items: bool = false),
```suggestion
    (docs_check_private_items: bool = false),
```

2023-11-19 21:44 UTC, GuillaumeGomez commented
I kinda had in mind something that could be generalized indeed. Should I make the change to make it specific for docs?

2023-11-19 22:28 UTC, blyxyas approved these changes
Hmmm, you're probably right, it should be a general configuration option. Thanks for the clarification.

LGTM, thanks! :heart:

2023-11-19 22:46 UTC, GuillaumeGomez commented
Great! I blessed the failing test so now waiting for the other PR to get merged. :)

2023-11-20 21:25 UTC, GuillaumeGomez commented
Rebased and fixed the merge conflict.

2023-11-21 09:49 UTC, blyxyas approved these changes
Meow

2023-11-21 10:27 UTC, GuillaumeGomez commented
I forgot the changelog once again... Added it!

2023-11-21 10:31 UTC, xFrednet commented
@bors retry

2023-11-21 10:35 UTC, xFrednet commented
@bors r- (I've changed the changelog entry and want to refresh the commit)

2023-11-21 10:38 UTC, xFrednet commented
@GuillaumeGomez before I r=blyxyas, could you run `cargo collect-metadata`? The previous bors CI complained about this check, if I saw it correctly

2023-11-21 10:38 UTC, GuillaumeGomez commented
What message you want in the commit exactly? (So I can update it)

2023-11-21 10:39 UTC, xFrednet commented
I wanted it to include links to the config and lint names. Usually we update the messages in the end, when the changelog is written, but some preprocessing never hurts ^^

2023-11-21 10:43 UTC, GuillaumeGomez commented
Ran the command and updated the commit message.

2023-11-21 10:44 UTC, xFrednet commented
Thank you for the quick updates :D

@bors r=blyxyas

2023-11-21 10:59 UTC, merged