Add new lint: `ref_as_ptr`
rust-lang/rust-clippy pull request #12087
Opened 2024-01-03 21:20 UTC by marcin-serwin

Fixes #10130

Added new lint `ref_as_ptr` that checks for conversions from references to pointers and suggests using `std::ptr::from_{ref, mut}` instead.

The name is different than suggested in the issue (`as_ptr_cast`) since there were some other lints with similar names (`ptr_as_ptr`, `borrow_as_ptr`) and I wanted to follow the convention.

Note that this lint conflicts with the `borrow_as_ptr` lint in the sense that it recommends changing `&foo as *const _` to `std::ptr::from_ref(&foo)` instead of `std::ptr::addr_of!(foo)`. Personally, I think the former is more readable and, in contrast to `addr_of` macro, can be also applied to temporaries (cf. #9884).

---

changelog: New lint: [`ref_as_ptr`]
[#12087](https://github.com/rust-lang/rust-clippy/pull/12087)

2024-01-09 04:04 UTC, asquared31415 commented
In my opinion `borrow_as_ptr` isn't particularly useful anyway, I think that this lint is more useful and has better readability.  The docs on `borrow_as_ptr` are also misleading because the code that it lints on *can't* cause the issues that it claims to prevent.

2024-01-11 19:44 UTC, xFrednet commented
I'm currently busy with exam season. Queen @blyxyas, would you do me the honer and review this PR? :D

r? @blyxyas

2024-01-11 19:45 UTC, blyxyas commented
?? I'll check `triagebot.toml`, but AFAIK I'm still in the reviewer rotation and not on vacation (maybe a bors bug?)

2024-01-11 19:49 UTC, xFrednet commented
Yeah IDK, was weird, does this work?

r? @xFrednet

2024-01-11 19:50 UTC, xFrednet commented
:joy: 

r? @blyxyas

2024-01-11 19:50 UTC, xFrednet commented
Lol, maybe it hasn't reloaded the configuration yet?

2024-01-11 19:50 UTC, blyxyas commented
Philipp reverted my change unassigning me as on-vacation.
I'll make another PR (=^w^=)

2024-01-13 12:19 UTC, blyxyas commented
Hmmm... How is this different from [`borrow_as_ptr`](https://rust-lang.github.io/rust-clippy/master/index.html#/borrow_as_ptr)? The example is the same for both lints

2024-01-14 01:02 UTC, blyxyas commented
Hmmm :thinking: I'm not really seeing the benefits of `from_ref` or `addr_of` over each other.
I think I'll nominate this, and let's see what the team thinks of this conundrum =^w^=

2024-01-14 01:36 UTC, asquared31415 commented
`from_ref` directly turns a reference into its pointer, it's sugar for `x as *const T` where `x: &T`.

`addr_of!` gets the address of a "place" which can be many different things, such as the address of a local (`addr_of!(my_owned_local)`), it can go through field projections (`addr_of!(my_struct.field)`), and it interacts with pointer dereferences to prevent making an intermediate reference.

They are useful in slightly different situations, specifically `addr_of!` can technically express more, but **because** it can do so many things, it's more cognitive load to do `addr_of!(*x)` to turn a `&T` into a `*const T` than it is to do `ptr::from_ref(x)`.

2024-01-25 00:28 UTC, blyxyas commented
Okis, so the conclusions from our [improvised meeting](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Meeting.3F) is that both lints can coexist. I'm still not to fond of this (e.g. what if someone used `#[warn(clippy::all)]` and `--fix`, or simply manually enabled them both?) but I'll review this because that's *what the council decided*

Meow meow, sorry for the long delay :pray:, I'll review it (at least start to do it) today

2024-01-26 13:24 UTC, blyxyas requested changes
Very good first iteration! Following [Philipp's suggestion](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Meeting.3F/near/418075026), and because I think that this new lint is more useful than `borrow_as_ptr` (but they lint in identical situations), could you move that lint into `restriction`?

I don't remember if there's a formal process to move a lint's category (⁎˃ᆺ˂), but I've asked about it. If there isn't a necessary process we didn't do, I'll merge this.

2024-01-29 22:25 UTC, blyxyas commented
Hmmm... you're right. We'll try with the second solution.
Make the `check` function return a boolean, and **only** if this check returns `false` (because the lint  didn't lint, possibly because of MSRV), we'll then check for `borrow_as_ptr`.

This way, both lints can be suspicious, and we don't have to prioritize one over the other.

2024-02-03 22:20 UTC, blyxyas approved these changes
Just a little bit of polish. After this little change, could you squash the commits?

2024-02-04 16:28 UTC, blyxyas commented
@bors r+

2024-02-04 16:38 UTC, blyxyas commented
@bors r+

2024-02-04 16:58 UTC, blyxyas commented
@bors retry

2024-02-04 17:06 UTC, blyxyas commented
@bors retry

2024-02-04 17:15 UTC, merged