Document manifest options
rust-lang/rust-clippy pull request #12218
Opened 2024-01-30 22:47 UTC by jhpratt

All built-in cargo commands have this output included when run with `cargo foo --help`. Clippy is the only exception, so I have copied the text here. As far as I can tell, the flags come from Cargo itself and not clippy, but the user almost certainly does not care about that.

```text
Manifest Options:
      --manifest-path <PATH>  Path to Cargo.toml
      --frozen                Require Cargo.lock and cache are up to date
      --locked                Require Cargo.lock is up to date
      --offline               Run without accessing the network
```

2024-01-30 22:48 UTC, jplimack commented
🍠

2024-01-30 23:03 UTC, jhpratt commented
It appears as though angle brackets can't be used due to `color_print`, and digging into the source of that crate does not show any mechanism to escape the angle bracket. As such, I resorted to building the string in two parts. That necessitates an owned string, but that shouldn't be an issue given that the program is so short-lived.

2024-02-12 20:56 UTC, xFrednet commented
I like having these options listed there as well, nice catch :+1: 

@blyxyas I believe you added the colors with `color_print` did you run into a similar issue in your PR?

---

Sorry, this PR totally slipped my mind. If you don't get a respond within one or two weeks, you're welcome to ping the reviewer. Sometimes, notifications get lost.

2024-02-12 21:37 UTC, blyxyas commented
You can use << and >> to escape your angles.

2024-02-15 03:03 UTC, jhpratt commented
Thanks for that info. The PR has been updated to use that.

2024-02-16 20:05 UTC, blyxyas requested changes
Meow meow =^w^=

2024-02-16 20:05 UTC, blyxyas commented on src/main.rs
> +    --offline               Run without accessing the network
You can use `cargo run --bin cargo-clippy -- --help` to check the results (the manifest options didn't have color)

```suggestion
<green,bold>Manifest Options:</>
    <cyan,bold>--manifest-path</> <cyan><<PATH>></>  Path to Cargo.toml
    <cyan,bold>--frozen</>                Require Cargo.lock and cache are up to date
    <cyan,bold>--locked</>                Require Cargo.lock is up to date
    <cyan,bold>--offline</>               Run without accessing the network
```

2024-02-18 22:09 UTC, jhpratt commented
Committed the suggestion as-is :slightly_smiling_face:

2024-02-18 23:12 UTC, blyxyas approved these changes
Could you squash these commits? I think that this is merge-ready (Also, if you have a machine at hand, could you test that the colors are correct, I sadly cannot test it visually)

2024-02-19 09:20 UTC, flip1995 commented
Just tested the colors. All LGTM.

2024-03-01 12:01 UTC, blyxyas commented
I've manually squashed the commits, the author seems to be busy.
Thanks for the contribution! :heart:

@bors r+

2024-03-01 12:09 UTC, blyxyas commented
@bors retry

2024-03-01 12:21 UTC, merged

2024-03-02 03:21 UTC, jhpratt commented
On the contrary, I just forgot :sweat_smile: In my head I remembered needing to test the colors, but that was verified. I forgot about squashing it.