WIP: Add a lint that detects non-portable usize literals
rust-lang/rust-clippy pull request #12347
Opened 2024-02-25 14:50 UTC by alexanderkjall

First lint I write, so I thought I should start with a minimal version and get feedback on it before spending the time fleshing it out.

I'm doing some packaging of rust crates for Debian in my spare time, and that results in running the builds and unit-tests for crates on more architectures than the author typically have access to, and there are a number of common mistakes that makes code nonportable.

Not thinking about `usize` and `isize` sizes are maybe the most common error.

One example of the issues that I would like to prevent is here: https://gitlab.com/sequoia-pgp/sequoia-chameleon-gnupg/-/issues/41

Since this codebase is very new to me, I would love feedback on everything.

I also realize that there are a large number of cases that isn't caught by this lint, but as mentioned before, I would rather get an early round of feedback.
---
changelog: [`usize_unportable_32_bit_literal`]: Add a lint that detects usize assignments that are not portable to 32bit architectures

2024-02-25 17:18 UTC, PatchMixolydic commented
On that note, there should probably be a separate pedantic/restriction lint for code that isn't portable to targets with [16-bit `{u,i}size`](https://doc.rust-lang.org/reference/types/numeric.html#machine-dependent-integer-types).

2024-02-25 18:17 UTC, alexanderkjall commented
yes, I agree, I think that might be a quite different usecase as 16 bit imposes a lot tighter restrictions, so it would make sense to have them as sepparate lints.

2024-03-12 05:12 UTC, Jarcho requested changes

2024-03-12 05:12 UTC, Jarcho commented on clippy_lints/src/usize_unportable_32_bit_literal.rs
> +}
This should use `map.parent_iter().any(...)`. Statements can have attributes, so you can't just use the parent item. Expression cannot have attributes, so you can skip the initial node (the function name also implies you do this).

2024-03-12 05:12 UTC, Jarcho commented on clippy_lints/src/usize_unportable_32_bit_literal.rs
> +    correctness,
This should be suspicious at most. We really need a portability category.

2024-05-16 15:47 UTC, J-ZhengLi commented
Hey @alexanderkjall, this is a ping from triage.

This PR is labeled WIP but there hasn't been any activity for some time, therefore I'm just here to make sure that you're still working on it and not stuck. 😃

2024-05-17 08:59 UTC, alexanderkjall commented
@J-ZhengLi Thanks for the ping, I still intend to see this through, but have gotten very busy with some other things in my life the last two months and that will continue for another one or so. No hard feelings if you want to close this or someone else want to work on the idea :)

2024-05-17 09:43 UTC, J-ZhengLi commented
> ...I still intend to see this through, but have gotten very busy with some other things in my life the last two months and that will continue for another one or so. No hard feelings if you want to close this or someone else want to work on the idea :)

That's very understandable~ I'll go ahead close this for now, but you can always re-open it when you got time.

You may open a new issue on this idea and assign yourself with `@rustbot claim` if you want to "lock it" 😄. If you need more help, you are welcome to ask people in the [clippy stream on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy).

@rustbot label +S-inactive-closed

2024-05-17 09:44 UTC, closed without merging