new restriction lint: `division_remainder_used`
rust-lang/rust-clippy pull request #12451
Opened 2024-03-10 00:06 UTC by Jacherr

Fixes https://github.com/rust-lang/rust-clippy/issues/12391

Introduces a restriction lint which disallows the use of `/` and `%` operators on any `Int` or `Uint` types (i.e., any that use the default `Div` or `Rem` trait implementations). Custom implementations of these traits are ignored.

changelog: Add new restriction lint `division_remainder_used`

2024-03-10 00:08 UTC, Jacherr commented
@tarcieri The example I included is extremely basic and not necessarily relevant to the lint itself; however, I'm no cryptography expert and found the example you provided in the original issue to be a bit long and specific (and also uses someone else's code).
 
If you can think of a better (ideally short) example than `10 / 2` -> `10 >> 1` I'd be more than willing to include it! Cheers

2024-03-11 07:49 UTC, hamirmahal commented on clippy_lints/src/division_remainder_used.rs
> +    /// when performed on any integer types using the default Div and Rem trait implementaions.
```suggestion
    /// when performed on any integer types using the default Div and Rem trait implementations.
```

2024-03-11 07:50 UTC, hamirmahal requested changes

2024-03-11 07:50 UTC, hamirmahal commented on clippy_lints/src/division_remainder_used.rs
> +    /// when performed on any integer types using the default Div and Rem trait implementaions.
```suggestion
    /// when performed on any integer types using the default Div and Rem trait implementations.
```

2024-03-11 11:21 UTC, Manishearth commented
r? rust-lang/clippy 

still a bit busy, redirecting reviews

2024-03-11 11:22 UTC, Manishearth commented on clippy_lints/src/division_remainder_used.rs
> +    pub DIVISION_REMAINDER_USED,
nit: INTEGER_DIVISION_REMAINDER_USED

2024-03-11 11:28 UTC, tarcieri commented
@Jacherr the specific example doesn't really matter as long as it covers usages of division / remainder. I just picked a real-world one to illustrate what the problem looked like in the wild and how it was fixed.

2024-03-17 08:09 UTC, llogiq commented
Thank you!

@bors r+

2024-03-17 08:17 UTC, merged

2024-03-18 15:22 UTC, tarcieri commented
A bit late, but we noticed there should potentially be an exception to this for operations which are exclusively on constants and/or which are statically known to always be in a `const` context.

It's fine as-is, but operations which are only on constants would be considered a false positive for cryptographic purposes.

I can open a separate issue for that if it's helpful.