Disable `cast_lossless` when casting to u128/i128 from any (u)int type
rust-lang/rust-clippy pull request #12496
Opened 2024-03-15 23:10 UTC by Jacherr

Fixes https://github.com/rust-lang/rust-clippy/issues/12492

Disables `cast_lossless` when casting to u128 or i128 from any int or uint type. The lint states that when casting to any int type, there can potentially be lossy behaviour if the source type ever exceeds the size of the destination type in the future, which is impossible with a destination of u128/i128.

It's possible this is a bit of a niche edge case which is better addressed by just disabling the lint in code, but I personally couldn't think of any good reason to still lint in this specific case.

changelog: FP: `cast_lossless`: disable lint when casting to u128/i128 from any (u)int type

2024-03-16 14:50 UTC, Alexendoo commented
I think the lint still applies here, the message could be updated but replacing a lossless cast with `from` is still a good suggestion

The type of the RHS could be changed in the future for example to a lossy cast

2024-03-18 07:17 UTC, blyxyas requested changes
Meow meow meow =^w^=

2024-03-18 07:17 UTC, blyxyas commented on clippy_lints/src/casts/cast_lossless.rs
> +            && (matches!(cast_to.kind(), ty::Int(IntTy::I128)) || matches!(cast_to.kind(), ty::Uint(UintTy::U128))))
Casting from a  `u128` to a `i128` could be dangerous. `u128` is the only data type that we can be sure that they won't cause an error.

```suggestion
            && matches!(cast_to.kind(), ty::Uint(UintTy::U128))
```

2024-03-20 12:23 UTC, blyxyas approved these changes
Sorry for the delay, I actually viewed this change the day you committed it but forgot to approve it :sweat_smile:

LGTM, thanks! :heart: Could you squash the commits into one?

2024-03-20 23:07 UTC, blyxyas commented
@bors r+

2024-03-20 23:17 UTC, merged

2024-06-13 16:01 UTC, TomFryersMidsummer commented
I'm not sure this should have been turned off. To expand on what @Alexendoo wrote:

This lint guards against two possible changes which would make the cast lossless.
1. Changing the source type to a larger one.
2. Changing the destination type to a smaller one.

While `u128` is indeed immune to the first problem, it's (particularly) susceptible to the second.

For instance, take this code.
```rust
type Id = u128;

fn from_database_id(x: u64) -> Id {
    x as Id
}
```
If `Id` were to be made a `u32`, `from_database_id` would no longer be injective, which could cause a bug. Using `Id::from` would prevent this.

2024-06-13 16:41 UTC, smoelius commented
> If `Id` were to be made a `u32`, `from_database_id` would no longer be injective, which could cause a bug.

Your concern is valid, but I think [cast_possible_truncation](https://rust-lang.github.io/rust-clippy/master/#/cast_possible_truncation) would fire in that case ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c066c96e63c5bb9996fea7c212b767f6)).

(I should have mentioned this in #12492.)

2024-06-13 17:45 UTC, Alexendoo commented
If anything that triggers `cast_lossless` becomes lossy it would trigger one of the other `cast_` lints (unless we're missing a case)

2024-06-13 23:38 UTC, smoelius commented
> If anything that triggers `cast_lossless` becomes lossy it would trigger one of the other `cast_` lints (unless we're missing a case)

I am willing to believe that, but is that an argument for keeping things the way they were? Could you explain?

2024-06-14 13:02 UTC, Alexendoo commented
It was to say that it's consistent with the other `cast_lossless` cases and isn't a reason to remove `as u128`

My view of it is the lint suggests replacing `n as T` with `T::from(n)` where possible to prevent future changes to `n` or `T` from causing unexpected behaviour. It also benefits the reader as they no longer have to consider if there is truncation/wrapping/etc happening

There are lints to catch these potentially unexpected casts, but they're all in `pedantic` and often `#[allow]`d anyway because e.g. `T::try_from(n).unwrap()` is a bit ugly

For the suggestion of replacing `n as u128` with `u128::from(n)` specifically it's true that no change to `n` can cause truncation to occur but that's not the only thing it protects against. As mentioned a change to the destination type (potentially through an alias) may cause issues

But also changes to the type of `n` can cause issues, if it becomes a signed integer type the `from` version will become a compile error and have you consider how you want to handle negatives. The `as` cast could be the answer to that, but you don't always want sign extension or the 2's complement form

2024-06-14 14:16 UTC, smoelius commented
Thank you very much for explaining. I think this is the main point where we disagree:

> As mentioned a change to the destination type (potentially through an alias) may cause issues

I agree this could happen, but it feels remote. To me, a change the type of the expression seems far more likely, and flagging such possibilities is where the lint really provides value.

Having said that, this is not a hill I'd want to die on. So thank you again for taking the time to write https://github.com/rust-lang/rust-clippy/pull/12496#issuecomment-2167993288.

2024-06-14 18:51 UTC, Alexendoo commented
Thanks, there's a while until the next meeting so let's just go with a poll since it's split:

https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Should.20.60as.20u128.60.20trigger.20cast_lossless

2024-06-16 10:33 UTC, smoelius commented
@Alexendoo Thank you for opening the poll.

@blyxyas Thank you for reviewing this PR.

@Jacherr Thank you jumping on my issue and resolving it. I'm sorry that your contribution will likely be reverted.