Add `check_self_items` setting for `needless_pass_by_ref_mut` lint
rust-lang/rust-clippy pull request #12648
Opened 2024-04-08 13:31 UTC by GuillaumeGomez

Fixes #12589.

This adds a `check_self_items` setting to allow the `needless_pass_by_ref_mut` lint to check for `&mut self` items.

changelog: Add `check_self_items` setting for `needless_pass_by_ref_mut` lint

2024-04-10 13:41 UTC, klensy commented
Should fix https://github.com/rust-lang/rust-clippy/issues/9591 too?

2024-04-10 14:09 UTC, GuillaumeGomez commented
Ah indeed.

2024-04-10 22:03 UTC, Manishearth requested changes
it's unclear to me that a config is actually the solution here. we should first try to better understand the problem space.

2024-04-12 13:34 UTC, klensy commented
> it's unclear to me that a config is actually the solution here. we should first try to better understand the problem space.

For start, you can read linked issues, https://github.com/rust-lang/rust-clippy/issues/9591, https://github.com/rust-lang/rust-clippy/pull/10900#issuecomment-1591104585

2024-04-13 08:34 UTC, Manishearth commented
Yes, I'm not convinced that that is a case not better served with targeted `allow`s.

For it to be a config I'd need to see a strong reason why this needs to be a _codebase-wide_ decision.

2024-04-13 08:45 UTC, klensy commented
> Yes, I'm not convinced that that is a case not better served with targeted `allow`s.

Targeted `allow`s - what you mean? If i currently want to lint `&mut self` - there is no way to do this. This lint more useful for analysis of code (and for analysis i want to see more suggestions, including `&mut self`s), not for automatically fixing all suggested things. Besides, this lint is in nursery.

2024-04-13 09:22 UTC, Manishearth commented
Ok, but if this lint were to unconditionally lint `&mut self`, what is the reason for someone to wish to disable that aspect of the check _across the codebase_? I understand wanting to do it for a specific type where there are special semantic needs, but those cases are fixed with a very warranted `allow`.

Basically what is the benefit of a config over making this available all the time?

Sure, this lint is in nursery, but why do work we may decide to undo at some point? For the lint to get out of nursery these discussions need to happen at some point, and there's not a huge benefit of waiting on this one.

2024-04-13 09:54 UTC, GuillaumeGomez commented
> Ok, but if this lint were to unconditionally lint `&mut self`, what is the reason for someone to wish to disable that aspect of the check _across the codebase_? I understand wanting to do it for a specific type where there are special semantic needs, but those cases are fixed with a very warranted `allow`.

It's the other way around: this lint never lints `&mut self` and this PR adds a config to allow `&mut self` to be linted.

2024-04-13 14:33 UTC, Manishearth commented
Yes, I understand: _why does this have to be a config and not unconditional behavior_?

2024-04-13 14:42 UTC, GuillaumeGomez commented
Thanks for clarifying. I was able to find my original answer about it [here](https://github.com/rust-lang/rust-clippy/pull/10900#issuecomment-1591104585). Basically, you might want to keep `&mut self` to ensure that even though `self` is not used mutably, you want to restrain its access. Maybe it's too far fetched though. I don't have a strong opinion about it nor do I have a use case where I actually need this use case.

2024-04-13 15:12 UTC, Manishearth commented
Yes, why is that use case not adequately satisfied by `allow`? What is the reason to want to disable that for the entire crate? That's when you have a config.

And I don't think it's concrete enough.

2024-04-13 15:41 UTC, GuillaumeGomez commented
In short, I was trying to limit the scope of the lint as much as possible. That's the only backing to it. Like I said, we could enable it by default and instead have this config to disable this behaviour.

2024-04-13 16:11 UTC, Manishearth commented
Yeah in general config options expand the scope of a lint and need to have a strong reason

2024-04-16 13:45 UTC, GuillaumeGomez commented
Just to confirm: following your logic, if the config would be to disable the check on `self`, wouldn't it be the opposite of an expansion of a lint scope? Or did I misunderstood what you meant?

2024-04-16 15:39 UTC, Manishearth commented
No. I'm saying having a config in the first place, regardless of what it does, expands the scope of a lint because it's effectively multiple lints now. We should avoid that unless _both_ lints can be justified. I can't see a strong justification for the "no-lint-self" version of this lint.

2024-04-16 16:25 UTC, GuillaumeGomez commented
Makes sense. Gonna update this lint to check for `self` as well instead then.

2024-04-18 20:28 UTC, GuillaumeGomez commented
Closing in favor of https://github.com/rust-lang/rust-clippy/pull/12693.

2024-04-18 20:28 UTC, closed without merging