[`infinite_loops`]: fix suggestion error on async functions/closures
rust-lang/rust-clippy pull request #13608
Opened 2024-10-26 09:05 UTC by J-ZhengLi

closes: #12338

I intended to fix this in #12421 but got distracted by some other problems in the same lint, causing delaying the process of closing the actual issue. So here's a separated PR that only focus on the issue and nothing else.

---

changelog: [`infinite_loops`]: fix suggestion error on async functions/closures

2024-10-26 16:34 UTC, hamirmahal requested changes

2024-10-26 16:34 UTC, hamirmahal commented on clippy_lints/src/loops/infinite_loop.rs
> +/// Note: This function also take care of return type of async fn,
```suggestion
/// Note: This function also takes care of the return type of async fn,
```

2024-11-01 19:34 UTC, Alexendoo approved these changes

2024-11-01 19:34 UTC, Alexendoo commented
Thanks! Async fns strike again 👀

@bors r+

2024-11-01 19:44 UTC, merged