Add `unnecessary_debug_formatting` lint
rust-lang/rust-clippy pull request #13893
Opened 2024-12-29 01:26 UTC by smoelius

Fixes #12674, i.e., adds a lint to flag `Path`s printed with `{:?}`.

Nits are welcome.

changelog: Add `unnecessary_debug_formatting` lint

2024-12-29 01:28 UTC, smoelius commented
cc: @kornelski

2024-12-29 11:56 UTC, smoelius commented
@blyxyas Sorry for the CI failures and the force push. But I think the lint should be good now.

2024-12-30 22:32 UTC, kornelski approved these changes

2025-01-14 21:54 UTC, blyxyas requested changes
Great first patch!

2025-01-14 21:54 UTC, blyxyas commented on tests/ui/unnecessary_path_debug_formatting.rs
> +    println!("{:?}", &*deref_path);
```suggestion
    println!("{:?}", path); //~ unnecessary_debug_formatting
    println!("{:?}", path_buf); //~ unnecessary_debug_formatting

    let _: String = format!("{:?}", path); //~ unnecessary_debug_formatting
    let _: String = format!("{:?}", path_buf); //~ unnecessary_debug_formatting

    let deref_path = DerefPath { path };
    println!("{:?}", &*deref_path); //~ unnecessary_debug_formatting
```

2025-01-14 21:54 UTC, blyxyas commented on tests/ui/unnecessary_os_str_debug_formatting.rs
> +    let _: String = format!("{:?}", os_string);
```suggestion
    println!("{:?}", os_str); //~ unnecessary_debug_formatting
    println!("{:?}", os_string); //~ unnecessary_debug_formatting

    let _: String = format!("{:?}", os_str); //~ unnecessary_debug_formatting
    let _: String = format!("{:?}", os_string); //~ unnecessary_debug_formatting
```

2025-01-15 09:04 UTC, smoelius commented on clippy_lints/src/format_args.rs
> +    restriction,
I considered this. But I was concerned there could be legitimate reasons to print a path with debug formatting, and that having to `allow` them could get annoying.

I'll change it if you feel strongly.

2025-01-15 09:05 UTC, smoelius commented on clippy_lints/src/format_args.rs
> +        if !value.span.from_expansion()
Frankly, I'm not sure, though I don't think it would hurt.

You mention "new lints" but are there larger guidelines for when [`is_from_proc_macro`](https://doc.rust-lang.org/nightly/nightly-rustc/clippy_utils/fn.is_from_proc_macro.html) should be used?

2025-01-15 12:24 UTC, blyxyas commented on clippy_lints/src/format_args.rs
> +        if !value.span.from_expansion()
In general, everywhere. There are not many lints that we want to lint in procedural macros. Proc macros are outside of the user's control and could produce any arbitrary output based on any arbitrary input.

For example, a while back we had an issue that a `clap` procedural macro produced `let _ = _`, Clippy warned about that and the user was confused because there was nothing they could do apart from reporting it to either Clap or Clippy. I'm not sure if there's a case that we want to explicitly lint in procedural macros.

2025-01-15 13:09 UTC, kornelski commented on clippy_lints/src/format_args.rs
> +    restriction,
I think it'd be better in `pedantic`. 

This isn't a subjective restriction, but future-proofing for a feature that can disable `Debug` entirely, and a warning that Rust never promised any stable syntax of the `Debug` format. I've seen a couple of libraries assume the `Debug` format is a correct serialization of paths into Rust string syntax, which it is not, and it breaks on non-UTF-8. 

So it is pedantically warning about edge cases that may affect all programs.

2025-01-15 14:06 UTC, smoelius commented on clippy_lints/src/format_args.rs
> +    restriction,
OK. I'll change it.

2025-01-16 10:23 UTC, smoelius commented
@blyxyas I think I have addressed all of your comments thus far.

2025-01-16 17:41 UTC, samueltardieu commented on tests/ui/unnecessary_path_debug_formatting.rs
> +    println!("{:?}", path_buf); //~ unnecessary_debug_formatting
Could you add an inline format test as well?

```rust
    println!("{path_buf:?}"); //~ unnecessary_debug_formatting
````

(ditto for `OsStr`)

2025-02-05 15:36 UTC, blyxyas commented
Here's the FCP: https://rust-lang.zulipchat.com/#narrow/channel/257328-clippy/topic/FCP.3A.20unnecessary_debug_formatting

Alexendoo says: It should definitely note that there is a difference in the output.

2025-02-05 16:00 UTC, Alexendoo commented
> I agree, we should probably mention that there may be a difference between outputs. (Although in version 1.85 there is not)

I don't think anything changed in 1.85, `Debug` escapes various characters including `'` which is not uncommon in paths, it also adds double quotes where `.display()` does not

While `Debug`'s format is not stable it is documented as escaping the path in [`.display()`](https://doc.rust-lang.org/std/path/struct.Path.html#method.display), plus it's unlikely the wrapping `""` would be removed

2025-02-05 17:54 UTC, smoelius commented
I'm proposing to add this text to the description:
> Note that switching from `Debug` formatting to `Display` formatting will change how the `OsStr` or `Path` is shown. Escaped characters will no longer be escaped, and enclsoing quotes (`"`...`"`) will be removed.

Does this sound okay?

Where would you add this, under "Why is this bad?"?

2025-02-06 14:47 UTC, Alexendoo commented
I was thinking to add a diagnostic note

For the *Why is this bad?* angle you could phrase it from the perspective of not being able copy/paste a path correctly or click it in an integrated terminal if the characters are escaped

2025-02-06 15:31 UTC, smoelius commented
> I was thinking to add a diagnostic note
> 
> For the _Why is this bad?_ angle you could phrase it from the perspective of not being able copy/paste a path correctly or click it in an integrated terminal if the characters are escaped

I'll make both changes.

2025-02-07 10:39 UTC, smoelius commented
@Alexendoo Please tell me if what I pushed is not what you had in mind.

2025-02-25 20:14 UTC, blyxyas reviewed
Sorry for the delay, I was waiting for Alex's input on the change but taking a look at it I think it's very agreeable.

2025-02-26 01:19 UTC, smoelius commented
> Sorry for the delay, I was waiting for Alex's input on the change but taking a look at it I think it's very agreeable. LGTM, thanks! ❤️ Could you change the version to reflect the new current version and squash all commits?

No worries at all. Please let me know if there's a Clippy version I missed. And thank you for the review. 🙏

2025-02-26 13:43 UTC, blyxyas commented on clippy_lints/src/format_args.rs
> +    #[clippy::version = "1.86.0"]
We decide the rust version for new Clippy lints by viewing the output of `rustc -Vv` in `master` :eyes:
This should be 1.87.0 :cat:

2025-02-26 13:53 UTC, Alexendoo commented
Ah sorry, I thought I had replied to this thread

Yeah, LGTM

2025-02-26 14:27 UTC, smoelius commented on clippy_lints/src/format_args.rs
> +    #[clippy::version = "1.86.0"]
Oof. Sorry.

2025-02-26 15:03 UTC, blyxyas approved these changes
LGTM, thanks! :heart:

2025-02-26 15:11 UTC, merged