new `manual_option_as_slice` lint
rust-lang/rust-clippy pull request #13901
Opened 2024-12-29 18:44 UTC by llogiq

Hey folks. It's been a while since I added the `as_slice` method to `Option`, and I totally forgot about a lint to suggest it. Well, I had some time around Christmas, so here it is.

---

changelog: add [`manual_option_as_slice`] lint

2024-12-30 17:09 UTC, llogiq commented
r? @blyxyas

2025-01-19 21:31 UTC, llogiq commented on clippy_lints/src/manual_option_as_slice.rs
> +        match expr.kind {
No, I'll add an expansion check. Good catch!

2025-01-19 21:33 UTC, llogiq commented on clippy_lints/src/manual_option_as_slice.rs
> +fn is_none_arm(cx: &LateContext<'_>, arm: &Arm<'_>) -> bool {
There's a difference though: The version in `match_as_ref.rs` also checks if that arm's expression is `None` which we don't do here.

So I doubt it makes a lot of sense to split that. But I'll take the `matches!` part from there to shorten the code.

2025-01-20 23:05 UTC, blyxyas requested changes

2025-01-26 13:19 UTC, blyxyas approved these changes
LGTM, thanks! :heart: I'll open an FCP

2025-01-26 20:00 UTC, Alexendoo commented on clippy_lints/src/manual_option_as_slice.rs
> +        if span.from_expansion() || !self.msrv.meets(msrvs::OPTION_AS_SLICE) {
Could do with an extra MSRV check for const contexts as the method became const stable later on

2025-02-03 22:09 UTC, merged