Restrict `same_item_push` to suppress false positives
rust-lang/rust-clippy pull request #6016
Opened 2020-09-07 15:13 UTC by giraffate

It only emits a lint when the pushed item is a literal, a constant and an immutable binding that are initialized with those, as discussed in https://github.com/rust-lang/rust-clippy/pull/5997#pullrequestreview-483005186. 

Fix https://github.com/rust-lang/rust-clippy/issues/5985

changelog: Restrict `same_item_push` to literals, constants and immutable bindings that are initialized with those.

r? @ebroto

2020-09-07 22:47 UTC, ebroto requested changes
Thanks for addressing this so quickly!

I've left some comments, mostly style remarks and some new tests.

2020-09-07 22:47 UTC, ebroto commented on clippy_lints/src/loops.rs
> +                                                )
We should factor out the linting code. We could use e.g. an inner function like this:
```rust
    fn emit_lint(cx: &LateContext<'_>, vec: &Expr<'_>, pushed_item: &Expr<'_>) {
        let vec_str = snippet_with_macro_callsite(cx, vec.span, "");
        let item_str = snippet_with_macro_callsite(cx, pushed_item.span, "");

        span_lint_and_help(
            cx,
            SAME_ITEM_PUSH,
            vec.span,
            "it looks like the same item is being pushed into this Vec",
            None,
            &format!(
                "try using vec![{};SIZE] or {}.resize(NEW_SIZE, {})",
                item_str, vec_str, item_str
            ),
        )
    }
```

2020-09-07 22:47 UTC, ebroto commented on clippy_lints/src/loops.rs
> -                        if_chain! {
We can move the check in line 1152 (sorry github don't allow commenting on non-edited code) to the beginning of the function, so we can avoid doing some work if not necessary

```rust
    // Make sure that the push does not involve possibly mutating values
    if !matches!(pat.kind, PatKind::Wild) {
        return;
    }
```

2020-09-07 22:47 UTC, ebroto commented on clippy_lints/src/loops.rs
>                      if let ExprKind::Path(ref qpath) = pushed_item.kind {
I think this would be more readable using `match`

2020-09-07 22:47 UTC, ebroto commented on clippy_lints/src/loops.rs
> +                                    if let rustc_hir::Local { init: Some(init), .. } = parent_let_expr;
```suggestion
                                    if let Some(init) = parent_let_expr.init;
```
This can be simplified.

2020-09-07 22:47 UTC, ebroto commented on tests/ui/same_item_push.rs
> +    }
We could add a test (not linted) involving shadowing
```suggestion
    }
    
    let mut vec = Vec::new();
    let item = 42;
    let item = fun();
    for _ in 0..20 {
        vec.push(item);
    }
```

And define the called function outside `main`
```rust
fn fun() -> usize {
    42
}
```

2020-09-07 22:47 UTC, ebroto commented on tests/ui/same_item_push.rs
> +        vec17.push(item);
Let's move these two up with the rest of linted cases.

We should also move the first test down with the non-linted cases.

2020-09-07 22:47 UTC, ebroto commented on tests/ui/same_item_push.rs
> +
We should add simplified versions of the problematic cases of #5985 
* My other comment about shadowing should cover the first case involving a function call
* We could add a test in which the variable is initialized with a match expression.

2020-09-08 14:23 UTC, giraffate commented
Thanks for your review! I address these (Tests failed where it seems unrelated).

2020-09-08 21:34 UTC, ebroto commented
@bors r+

Thanks!

2020-09-08 21:54 UTC, merged