New Lint: disallowed_method
rust-lang/rust-clippy pull request #6081
Opened 2020-09-24 20:46 UTC by ilknarf

From https://github.com/rust-lang/rust-clippy/issues/6073

I added a `disallowed_method ` that works similar to `blacklisted_name`, e.g allows config-defined disallowed method calls.

This lint allows advanced users to patch in undesired method calls for specific projects. It basically uses the DefId of method calls and matches it to parsed strings. Is there an alternative approach that could use more easily digestible configuration strings?

All tests pass as expected except for a linting error on `ui/redundant_pattern_matching_option`, which I am not sure how to resolve since I don't think I changed anything affecting it.

changelog: none

2020-09-24 20:46 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @matthiaskrgr (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md) for more information.

2020-09-25 10:42 UTC, matthiaskrgr requested changes
Hi, thanks for the patch!
Some notes:

If you add "Fixes #6073" to pr description, the linked ticket will auto-close once the pr is merged.

The "changelog: none" line at bottom will later be used to auto-generate a changelog for clippy.
It should read something like "changelog: Add disallowed_method lint to warn on user-defined method calls" or something like that. :)

We try to keep merge commits to a minimum which is why we [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) branches instead of merging master into them.

2020-09-25 10:42 UTC, matthiaskrgr commented on clippy_lints/src/disallowed_method.rs
> +    "used disallowed method call"
This could be the same as the lint message: "use of disallowed method call"

2020-09-25 10:42 UTC, matthiaskrgr commented on clippy_lints/src/disallowed_method.rs
> +                        "Use of a disallowed method `{}`",
[lint messages](https://rustc-dev-guide.rust-lang.org/diagnostics.html?highlight=lint#diagnostic-structure) should not be capitalized

2020-09-25 10:42 UTC, matthiaskrgr commented on clippy_lints/src/disallowed_method.rs
> +                            .join("::"),
Making this a variable and using the var inside the `format!()` is clearer imo.

2020-09-25 14:29 UTC, flip1995 commented on clippy_lints/src/utils/conf.rs
> +    (disallowed_methods, "disallowed_methods": Vec<String>, ["disallowed_method::Foo::bad_method", "disallowed_method::Baz::bad_method", "disallowed_method::Quux::bad_method"].iter().map(ToString::to
I would keep the default set of methods empty here.

2020-09-25 14:29 UTC, flip1995 commented on clippy_lints/src/disallowed_method.rs
> +    /// foo.bad_method(); // Foo is disallowed
```suggestion
    /// // example code where clippy issues a warning
    /// foo.bad_method(); // Foo::bad_method is disallowed in the configuration
```

2020-09-25 16:13 UTC, ilknarf commented
Sorry for the force push, is it OK that I removed the useless tests since I removed the default values?

2020-09-26 14:46 UTC, ilknarf commented
The issues should be resolved

2020-09-26 20:46 UTC, matthiaskrgr approved these changes
LGTM!

2020-09-26 20:47 UTC, matthiaskrgr commented
Thanks!
@bors r+

2020-09-26 21:16 UTC, merged