Downgrade string_lit_as_bytes to nursery
rust-lang/rust-clippy pull request #6117
Opened 2020-10-05 19:35 UTC by dtolnay

Between #1402 (regarding `to_owned`) and #4494 (regarding `impl Read`), as well as other confusion I've seen hit in my work codebase involving string_lit_as_bytes (`"...".as_bytes().into()`), I don't think this lint is at a quality to be enabled by default.

I would consider re-enabling this lint after it is updated to understand when the surrounding type information is sufficient to unsize `b"..."` to &\[u8\] without causing a type error.

As currently implemented, this lint is pushing people to write `&b"_"[..]` which is not an improvement over `"_".as_bytes()` as far as I am concerned.

---

changelog: Remove string_lit_as_bytes from default set of enabled lints

2020-10-05 19:35 UTC, rust-highfive commented
r? @matthiaskrgr

(rust_highfive has picked a reviewer for you, use r? to override)

2020-10-05 19:40 UTC, dtolnay reviewed
CI failure appears unrelated.

```console
error[E0061]: this function takes 2 arguments but 3 arguments were supplied
  --> clippy_lints/src/redundant_clone.rs:89:14
   |
89 |             .into_engine(cx.tcx, mir, def_id.to_def_id())
   |              ^^^^^^^^^^^ ------  ---  ------------------ supplied 3 arguments
   |              |
   |              expected 2 arguments
```

2020-10-07 02:45 UTC, dtolnay commented
- Rebased on #6126 to maybe fix the build.

2020-10-07 02:57 UTC, dtolnay commented
Passed!

2020-10-08 07:47 UTC, ebroto requested changes
I agree that the suggestion is broken so it seems fair to downgrade it.

Could you please add a small note in the `Known problems` section explaining why it's in the nursery?

2020-10-08 11:56 UTC, dtolnay commented
Added documentation of known problems.

<br>

> > #### Known Problems:
> > `"str".as_bytes()` and the suggested replacement of `b"str"` are not equivalent because they have different types. The former is `&[u8]` while the latter is `&[u8; 3]`. That means in general they will have a different set of methods and different trait implementations.
> >
> > ```rust
> > fn f(v: Vec<u8>) {}
> >
> > f("...".as_bytes().to_owned()); // works
> > f(b"...".to_owned()); // does not work, because arg is [u8; 3] not Vec<u8>
> >
> > fn g(r: impl std::io::Read) {}
> >
> > g("...".as_bytes()); // works
> > g(b"..."); // does not work
> > ```
> >
> > The actual equivalent of `"str".as_bytes()` with the same type is not `b"str"` but `&b"str"[..]`, which is a great deal of punctuation and not more readable than a function call.

2020-10-08 21:33 UTC, ebroto commented
@bors r+

Thanks for the nice explanation of the problem

2020-10-08 21:54 UTC, merged