allow match in consts
rust-lang/rust-clippy pull request #6215
Opened 2020-10-24 14:18 UTC by llogiq

This extends our const handling to allow for `match`. Unsure how we'd test it, though, and we may want to extend it so we can add bindings to expressions *in* matches. Even so, I consider it a win.

r? @ebroto 
---

*Please keep the line below*
changelog: none

2020-10-24 16:04 UTC, llogiq commented
Errors seem unrelated, and I cannot reproduce them.

2020-11-04 23:52 UTC, ebroto commented
Sorry for the delay in getting this reviewed, I'm really short on time lately. This will be the next PR I'll review when I get some free time.

2020-11-07 17:09 UTC, llogiq commented
No worries. I'm also just trying to catch up while following RustFest global...

2020-11-10 22:08 UTC, ebroto requested changes
I think we should add tests covering each new possible case in an arbitrary lint that uses the `constant` function.

2020-11-10 22:08 UTC, ebroto commented on clippy_lints/src/consts.rs
> +                        self.match_bindings.truncate(outer_bindings);
I think this could be outside of the loop as `outer_bindings` will not change

2020-11-25 14:20 UTC, giraffate commented
ping from triage @llogiq. There seem some fixes left to be done. Could you have any update on this?

2020-11-26 22:34 UTC, llogiq commented
Yes, but I'll need some more time. If you want you can close and I can reopen when I get around to it.

2020-11-26 22:39 UTC, ebroto commented
>Yes, but I'll need some more time. If you want you can close and I can reopen when I get around to it.

I know my requested changes are kind of problematic, sorry about that! I just want to make sure we cover those new paths to avoid triggering bugs that are hard to find because we don't test them.

Feel free to close the PR if you don't find time to adress them currently.

2020-12-19 21:54 UTC, ebroto commented
I'm going to close this for now to clean up a bit the PR queue

2020-12-19 21:54 UTC, closed without merging

2021-01-07 14:58 UTC, flip1995 commented
@llogiq Can you move this branch to a fork, please? This is the only remaining branch, besides the necessary branches for CI, release, and deployment. cc #4745

2021-05-27 08:52 UTC, flip1995 commented
I pushed this branch to my fork: https://github.com/flip1995/rust-clippy/tree/const-match

I now delete the branch from this repo. We now only have branches necessary for CI, release and deployment in this repo.