WIP: Add `not_exhaustive_enough´ lint
rust-lang/rust-clippy pull request #6328
Opened 2020-11-12 23:00 UTC by jrqc

Fixes #5557
changelog: new lint `not_exhaustive_enough`

2020-11-23 15:24 UTC, Rantanen commented on clippy_lints/src/not_exhaustive_enough.rs
> +    ///     }
The point of `#[non_exhaustive]` is that the wildcard match is always required:
```suggestion
    ///         E::Third => {}
    ///         _ => {}
    ///     }
```

2020-11-24 01:16 UTC, ebroto requested changes
Thanks for the effort you've put into this! 

I did a first round of review, don't hesitate to ask for clarification if needed.

2020-11-24 01:16 UTC, ebroto commented on clippy_lints/src/not_exhaustive_enough.rs
> +        "Enum not exhaustive enough",
```suggestion
        "enum match is not exhaustive enough",
```
We generally avoid capitalizing the first letter

2020-11-24 01:17 UTC, ebroto commented
Also, my apologies for the delay in reviewing, I did not have much free time lately.

2020-11-24 01:40 UTC, Rantanen commented
I'm slightly concerned that the full use of this lint will be held back by inability to distinguish between:
- I want to only match these two items and don't care about the rest.
- I want to match everything, but need to use wildcard for `non_exhaustive`.

```rust
match io_error.kind() {
  ErrorKind::TimedOut => self.retry(),
  _ => return Err(io_error),  // This is intended to match all known and unknown kinds.
}
```

```rust
if let Some(Foo { x, .. /* don't care for the rest */ }) = maybe_foo {
  ..
}
```

These issues can always be ignored case-by-case with `#[allow(..)]` attributes on the statements, but if that has to be done frequently the added noise of said attributes might outweigh the benefits.

I don't really have any good solutions to this problem and I do feel having the lint as it is implemented here is better than not having it at all. :)

2020-11-24 14:22 UTC, jrqc commented
Thank you for the review! I will make the necessary changes as soon as possible

2020-11-24 21:08 UTC, ebroto commented
@Rantanen that's a very good point. 

The idea behind the lint is to warn in case new fields/variants are added, so it should target those cases where the user wanted to be as exhaustive as possible. But we don't know how the data structure looked like when the user wrote the code, so we can only approximate.

Some possible heuristics could be (although I'm not happy with any of them TBH):
* Warn only if a majority of the fields/variants are already included (i.e. >= n/2+1).
* Do not warn if only one field/variant is included (without taking wildcard/rest pattern into account).

2020-11-24 21:13 UTC, ebroto commented
If the lint turns out to be more annoying than helpful we can always turn it into a `restriction` lint.

2020-12-18 14:33 UTC, giraffate commented
ping from triage @jrqc. There seem to be some small fixes left to be done. Could you have any update on this?

2020-12-29 18:32 UTC, jrqc commented
Sorry about the delayed response @ebroto @giraffate 
I will update it today

2020-12-30 07:31 UTC, jrqc commented
@ebroto Made the necessary changes! Hope I didn't miss anything 
Again sorry about the late edit

2021-01-03 00:10 UTC, ebroto commented
>Sorry about the delayed response

No problem, thanks for sticking with it! I will try to review in the coming days.

2021-01-16 22:28 UTC, ebroto commented
r? @Manishearth (I'm leaving the team, so I'm reassigning my PRs to other active members)

2021-01-21 23:47 UTC, Manishearth commented
I'll review this when I get a chance, but I'm wondering: we're replicating a lot of the exhaustiveness checking logic in rustc, yeah? Can we use it, or make this lint a lint in rustc?

2021-01-29 23:21 UTC, Manishearth commented
@flip1995 what are your opinions on the above^ ?

2021-01-31 14:49 UTC, flip1995 commented
I don't really have an opinion on this, since I didn't review any of the exhaustiveness PRs AFAICR. I just can give a general answer: If we can share code with rustc, we should do that. But I don't know how code in Clippy or rustc looks like for exhaustiveness checks.

2021-01-31 22:16 UTC, Manishearth commented
@flip1995 so the thing is that rustc already has exhaustiveness checks, and this is a lint that was proposed in a Rust RFC, so it would both be _easy_ to implement in rustc and _make sense_. It feels weird to reimplement exhaustiveness checking in a partial way outside of rustc when we can have a perfect version of this lint in rustc.

2021-01-31 22:34 UTC, flip1995 commented
Yeah, agreed.

2021-02-16 23:51 UTC, giraffate commented
ping from triage @Manishearth. Do we still need discussion here?

2021-02-17 00:09 UTC, Manishearth commented
Yeah, sorry, I think we've discussed this and we shouldn't be doing this in clippy. It's worth filing a bug on rust-lang/rust to add such an allow-default lint. Sorry @jrqc!

2021-02-17 00:09 UTC, closed without merging

2021-04-18 14:27 UTC, jplatte commented
I can't find an issue about this lint at rust-lang/rust, did anybody end up creating one? Also, given that this won't be implemented in clippy, somebody should close the associated issue (#5557).