Fix rust-lang/rust#79255 - Incorrect try suggestion for float cast
rust-lang/rust-clippy pull request #6362
Opened 2020-11-22 00:11 UTC by nico-abram

changelog: Fix rust-lang/rust#79255 - Incorrect try suggestion for float literal cast ending in dot

2020-11-22 00:11 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @ebroto (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md) for more information.

2020-11-24 23:41 UTC, ebroto requested changes
I think it would be simpler if we just remove the dot instead. What do you think?

2020-11-25 01:40 UTC, nico-abram commented
Sounds good to me, simpler implementation and will keep the suggestions more uniform
I was just going off the issue saying `The correct suggestion is 3.0_f32`, will probably change it tomorrow

2020-11-25 09:36 UTC, iago-lito commented
@nico Hm, the truth is that I didn't even think that `3_f32` was also valid ^ ^"

So IIUC now the question is which formatting to suggest among:
- `3.0_f32`
- `3_f32`
- `3.0f32`
- `3f32`
right?

Well, I'm not sure whether there are official recommendations regarding this.
My personal feeling is that Rust likes to favor explicitness and readability, so I think the first option, `3.0_f32`, is the most consistent suggestion.

---

Alternately, picking the option that yields the formatting maybe-closest from what the user had in mind is also interesting, like:
- `3. as f32` would suggest `3_f32`
- `3 as f32` would suggest `3f32`
- `3.0 as f32` would suggest `3.0_f32` or `3.0f32`

but that feels messy. I'd rather expect `rust` not to try to accomodate my thoughs and just spit out the most explicit + readable option.

---

Even more alternately, defer the question to `rustfmt` options. Once the user has defined the one they like best in their `rustfmt.toml`, either they apply the fix then run a fmt pass, or the fix is super-sophisticated and goes read these options to directly decide which formatting to suggest.

---

To be clear, I also think most of this is overkill. My preferred solution is to just 
suggest `3.0_f32` and call it a day ;)

2020-11-26 08:40 UTC, ebroto approved these changes
@iago-lito I think this solution is good because it doesn't need to change a lot the current implementation, note that `_` is always added.

Also, `.0` is kind of redundant given that we are specifying the type explicitly.

2020-11-26 08:41 UTC, ebroto commented
@bors r+

Thanks!

2020-11-26 09:01 UTC, merged