add "WebGL" to doc_valid_idents
rust-lang/rust-clippy pull request #6388
Opened 2020-11-27 00:50 UTC by kawogi

I added "WebGL" along the lines of the existing "OpenGL" to the whitelist of `doc_markdown` as I found this to be a pretty common term.

changelog: Whitelist "WebGL" in `doc_markdown`.

2020-11-27 00:50 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @ebroto (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md) for more information.

2020-11-28 20:11 UTC, kawogi commented
I'm new to this. How do we continue? The error seems to be unrelated to my change.

2020-11-28 21:19 UTC, ebroto requested changes
Could you please add a test for this, like in [this commit](https://github.com/rust-lang/rust-clippy/commit/22c994061359aa9e0e08e44cd698dbfc6553834c)?

---

About the error, I think it should go away after rebasing on top of the current master

2020-11-29 13:56 UTC, ebroto commented
And by the way, welcome to Clippy! :)

2020-12-13 14:49 UTC, giraffate commented
ping from triage @kawogi. Do you have any questions on how to proceed here?

2020-12-16 03:51 UTC, kawogi commented
I should find some time to complete this in the upcoming days.

2021-01-04 00:35 UTC, giraffate commented
ping from triage @kawogi. Could you have any update on this?

2021-01-16 22:28 UTC, ebroto commented
r? @flip1995 (I'm leaving the team, so I'm reassigning my PRs to other active members)

2021-01-17 13:59 UTC, giraffate commented
ping from triage @kawogi. According to triage procedure, I'm closing this because 2 weeks have passed with no activity. If you have more time to work on this, feel free to reopen this.

2021-01-17 13:59 UTC, closed without merging

2021-01-17 22:03 UTC, kawogi commented
Sorry for the delay!
I added the requested test and would like update this pull request. How can this be re-opened or am I required to file another pull-request?

2021-01-17 23:26 UTC, giraffate commented
Thanks for opening new PR!

2023-10-10 18:33 UTC, jonboh commented
@rustbot label -S-inactive-closed