Fix false positive in write_literal and print_literal due to numeric literals
rust-lang/rust-clippy pull request #6408
Opened 2020-12-01 15:28 UTC by pro-grammer1

changelog:
Stopped numeric literals from being linted by write_literal and print_literal.

Fixes

2020-12-01 15:28 UTC, rust-highfive commented
r? @ebroto

(rust-highfive has picked a reviewer for you, use r? to override)

2020-12-01 15:39 UTC, pro-grammer1 commented
Fixes #6335

2020-12-08 22:47 UTC, ebroto requested changes
Just some nits. 

Also, the reference file for the tests needs to be updated because the `stderr` files have changed, as we are not linting if the literals are ints/floats. To do this, you can run the `tests/ui/update-all-references.sh` script.

2020-12-08 22:47 UTC, ebroto commented on clippy_lints/src/write.rs
> +                    } =>
```suggestion
                ExprKind::Lit(lit) if !matches!(lit.kind, LitKind::Int(..) | LitKind::Float(..)) => {
```
We can simplify using `matches!()`

2020-12-08 22:47 UTC, ebroto commented on clippy_lints/src/write.rs
> +                        };
```suggestion
                        if !matches!(lit.kind, LitKind::Int(..) | LitKind::Float(..));
```
Same here

2020-12-22 23:41 UTC, giraffate commented
ping from triage @pro-grammer1. There seems to be some fixes left to be done. Do you have any questions on how to preceed here?

2021-01-05 23:30 UTC, giraffate commented
ping from triage @pro-grammer1. According to the triage procedure, I close this because there has no activity in 2 weeks from previous ping. If you have more time to work on this, feel free to reopen.

2021-01-17 09:05 UTC, pro-grammer1 commented
I've made the changes, so I would like to reopen this.

2021-01-17 13:52 UTC, giraffate commented
Thanks for taking time to work on this! I reopen this.

2021-01-18 09:19 UTC, pro-grammer1 commented
I've made the suggested changes and updated the tests. Is there anything else I should do?

2021-01-21 14:11 UTC, flip1995 reviewed
Oli was faster, but I have a comment anyway :smile:

2021-01-21 14:11 UTC, flip1995 commented on tests/ui/crashes/ice-3891.stderr
> +   = help: the suffix must be one of the numeric types (`u32`, `isize`, `f32`, etc.)
Why did this change? This is a rustc lint and should be unaffected by a Clippy PR. (rebase gone wrong?)

2021-01-21 14:19 UTC, oli-obk commented
@bors r+

2021-01-21 14:34 UTC, merged