match_like_matches_macro: strip refs in suggestion
rust-lang/rust-clippy pull request #6532
Opened 2021-01-01 16:58 UTC by matthiaskrgr

fixes #6503

changelog: match_like_matches_macro: strip refs in suggestion (#6503)

2021-01-01 16:58 UTC, rust-highfive commented
r? @ebroto

(rust-highfive has picked a reviewer for you, use r? to override)

2021-01-02 11:56 UTC, alex-700 commented
@matthiaskrgr thanks for PR! But this implementation is not accurate enough. It should also think about a using the variable after `matches!` macro. For example the following code does not compile and using reference here is meaningful. 
```rust
enum A { X, Y }

fn foo(x: A) {}

fn main() {
    let z = A::X;
    let _ = matches!(z, A);
    foo(z);
}
```

2021-01-02 23:30 UTC, ebroto requested changes
@alex-700 makes a good point, although I was a bit confused at the beginning by the example because `A` is a variable binding and not lowercase. Since the scrutinee is not a reference anymore and the pattern is not a reference pattern, the binding moves the value. The same case slightly modified:

```rust
struct S(i32);

fn fun(_val: Option<S>) {}

fn main() {
    let val = Some(S(42));
    
//    let _res = match &val {
//        Some(_a) => true,
//        _ => false,
//    };

    let _res = matches!(val, Some(_a));
    fun(val);
}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a300260aca82a7cfb8cefa44a0c662aa))

---

The current implementation would also fail if the match uses a reference pattern, so match ergonomics does not apply. Consider the following case:
```rust
struct S(i32);

fn fun(_val: Option<S>) {}

fn main() {
    let val = Some(S(42));
    
//    let _res = match &val {
//        &Some(ref _a) => true,
//        _ => false,
//    };

    let _res = matches!(val, &Some(ref _a));
    fun(val);
}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=600dcb56bbd76d943aaa916a04843558))

This would yield a `mismatched types` error
```
error[E0308]: mismatched types
  --> src/main.rs:11:30
   |
11 |     let _res = matches!(val, &Some(ref _a));
   |                         ---  ^^^^^^^^^^^^^ expected enum `Option`, found reference
   |                         |
   |                         this expression has type `Option<S>`
   |
   = note:   expected enum `Option<S>`
           found reference `&_`
```

2021-01-03 19:31 UTC, matthiaskrgr commented
I think I got all the options covered now..?
There's still some cases where we could remove a & but the suggestion will still compile.

2021-01-16 22:29 UTC, ebroto commented
r? @llogiq (I'm leaving the team, so I'm reassigning my PRs to other active members)

2021-01-21 18:34 UTC, llogiq commented
From my point of view, this looks like a very solid improvement, also the tests seem to cover all cases. Thank you!

@bors r+

2021-01-21 19:05 UTC, merged