useless use of format! should return function directly
rust-lang/rust-clippy pull request #7092
Opened 2021-04-15 21:40 UTC by basavesh

fixes #7066 

changelog:
wrap the content in the braces.

r? @giraffate

2021-04-15 21:40 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @giraffate (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md) for more information.

2021-04-15 22:33 UTC, basavesh commented on clippy_lints/src/format.rs
> +                    return Some(format!("({}).to_string()", s_expand))
Probably this change is also not required.

2021-04-16 03:15 UTC, giraffate requested changes
Thanks for your work, and welcome to Clippy!

Parentheses should be put only when it's needed, not all. `maybe_par` method in `utils` may be useful for this case.

Also, Can a test like the one described in the related issue be added?

2021-04-16 12:57 UTC, basavesh commented
fixes https://github.com/rust-lang/rust-clippy/issues/7078

2021-04-19 13:41 UTC, giraffate approved these changes
It looks good, thanks!

Can you squash commits?

2021-04-19 23:06 UTC, giraffate commented
@bors r+

Thanks!

2021-04-19 23:21 UTC, merged