Add new line: `rc_mutex`
rust-lang/rust-clippy pull request #7316
Opened 2021-06-04 02:53 UTC by lengyijun

changelog:
Add new lint `rc_mutex`. 

It lints on `Rc<Mutex<T>>`.  

`Rc<Mutex<T>>` should be corrected to `Rc<RefCell<T>>`

2021-06-04 02:53 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @llogiq (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md) for more information.

2021-06-05 08:01 UTC, llogiq requested changes
This should work well enough as a restriction lint. However, I think the suggestion is incomplete and the tests should be fleshed out more.

2021-06-05 14:12 UTC, lengyijun commented on tests/ui/rc_mutex.rs
> +pub fn test1<T>(foo: Rc<Mutex<T>>) {}
Could you please check if I added correct test in my latest commit?
I'm not sure I did it right.

2021-06-05 14:20 UTC, llogiq commented on tests/ui/rc_mutex.rs
> +fn main() {}
How about calling `test1`, `test2`, etc. from here?

This is something the lint might want to consider, btw., and also the reason not to apply it automatically.

2021-06-08 15:42 UTC, flip1995 commented
Is there an issue open for this lint? Or was it discussed in any other place beforehand? If so, please link to it in the PR description.

2021-06-09 05:24 UTC, lengyijun commented
There is no related issue and discussion.

2021-06-10 05:28 UTC, llogiq commented on clippy_lints/src/types/mod.rs
> +    /// **Known problems:** None.
I think there may be instances where combining generics and traits could require this actual type combination, and following the suggestion would make it impossible to implement the traits.

We should consider those cases false positives and make a note of a possible problem. I don't think this problem is worrisome for the lint (it's unlikely to happen in practise), but we should note it nonetheless.

2021-06-19 13:30 UTC, llogiq commented
Sorry for letting you wait for so long. I had some $life keeping me busy.

I'd like a more fleshed out explanation of the possible false positives. How about: "Sometimes combining generic types can lead to the requirement that a type use `Rc` in conjunction with `Mutex`. We must consider those cases false positives, but alas they are quite hard to rule out. Luckily they are also rare."

2021-07-03 10:16 UTC, llogiq commented
Thank you! @bors r+

2021-07-03 10:37 UTC, merged