lintcheck directly uses local crate instead of copying when provided with a crate path
rust-lang/rust-clippy pull request #7521
Opened 2021-07-31 08:41 UTC by rukai

changelog: none

When lintcheck is run on local crates it copies the crate to `target/lintcheck/sources/crate_name` on the first run only.
Then in subsequent runs of lintcheck it reuses this same copy.
This caching behaviour makes sense when dealing with immutable crates.io releases and git commits.
However it is quite surprising that the changes to my local crate are not used when I run lintcheck.

To fix this I removed the copy, instead clippy runs directly off the provided crate folder.
I have tested this and have not observed any negative effects from doing this.
But maybe i'm missing something as im not familiar with clippy!

Alternatively we could make it copy the entire crate every run, but that seems problematic to me as multi-gigabyte target folders will take a long time to copy and wear down SSDs for developers who frequently run lintcheck.

2021-07-31 08:41 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @camsteffen (or someone else) soon.

Please see [the contribution instructions](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md) for more information.

2021-07-31 18:58 UTC, camsteffen approved these changes
LGTM. @flip1995 can you also take a look? I don't have much experience with lintcheck.

2021-08-01 20:16 UTC, matthiaskrgr commented
Hmm, I think the reason for copying the crate every time is so that lintcheck can run clippy with --fix mode without having to worry about the crates state, but I am not 100% certain.

Does that still work?

2021-08-01 20:57 UTC, camsteffen commented
Ah I didn't realize there is a `--fix` feature. Indeed that may be surprising if lintcheck actually applies fixes. I also just realized that we risk modifying `Cargo.lock`. I have a list of ideas, just brainstorming.

* Only copy the directory in fix mode
* Use [`cargo_metadata`](https://crates.io/crates/cargo_metadata) to identify target directories and avoid copying them.
* Add a `--update-paths` flag to re-copy paths.
* Tell the user if a cached path is used.
* Use `cargo --locked` to avoid updating `Cargo.lock`
* Add a `--path-direct-mode` (straw man) to run directly in paths and don't worry about modifying stuff

I do feel that copying target directories is pretty bad.

2021-08-02 09:34 UTC, flip1995 commented
@matthiaskrgr is the one to ask about the lintcheck tool. So I'm passing this decision to him. :+1:

2021-08-08 19:55 UTC, camsteffen commented
@rukai I don't think this can be merged as is because we can't modify paths. Do you want to pursue any of the ideas mentioned?

2021-08-08 23:48 UTC, rukai commented
I'm happy to implement some of these ideas. But I wanted to know which direction we were taking before I started work on it.

2021-08-09 02:41 UTC, camsteffen commented
Instead of cargo metadata, I think a better option is to use gitignore. So I'd say do that and/or `--update-paths`.

2021-08-09 02:48 UTC, camsteffen commented
Ooh here's an even easier idea - look for CACHEDIR.TAG files.

2021-08-15 02:48 UTC, rukai commented
I went for the CACHEDIR.TAG approach.
Happy to try other approaches if we decide thats not enough.

The copying logic completely ignores any symlinks.

2021-08-15 23:15 UTC, camsteffen requested changes

2021-08-15 23:15 UTC, camsteffen commented on lintcheck/src/main.rs
> +                std::fs::remove_dir_all(&dest_crate_root).ok();
Unwrap if the error is not `NotFound`. Also add a `println!` for if the directory is found and removed.

2021-08-16 00:13 UTC, camsteffen approved these changes
LGTM. Can you please squash commits?

2021-08-16 00:18 UTC, rukai commented
squashed

2021-08-16 00:20 UTC, camsteffen commented
Thanks! @bors r+

2021-08-16 00:33 UTC, merged