Expand box_vec lint to box_collection
rust-lang/rust-clippy pull request #7693
Opened 2021-09-20 08:16 UTC by F3real

fixed #7451 

changelog:
Report unnecessary boxing for collections

2021-09-20 08:16 UTC, rust-highfive commented
r? @Manishearth

(rust-highfive has picked a reviewer for you, use r? to override)

2021-09-20 16:46 UTC, F3real commented
@flip1995 it seems that `remark` failure is related to mention of `box_vec` in CHANGELOG.md. Should we also remove mentions from changelog? It feels a bit weird.

2021-09-20 20:16 UTC, Manishearth requested changes

2021-09-20 20:16 UTC, Manishearth commented on clippy_lints/src/lib.rs
> +        types::BOX_COLLECTION,
also should add this rename to `register_renamed` below

2021-09-22 16:04 UTC, Manishearth approved these changes

2021-09-22 16:05 UTC, Manishearth commented
@F3real you don't have to remove mentions, you just need to make sure the `box_vec` link reference exists and links to `box_collections`

2021-09-22 22:07 UTC, Manishearth approved these changes

2021-09-22 22:09 UTC, Manishearth commented
@bors r+

2021-09-22 22:13 UTC, Manishearth commented
@bors retry

2021-09-22 22:25 UTC, merged