Handle implicit named arguments in `useless_format`
rust-lang/rust-clippy pull request #8295
Opened 2022-01-15 19:35 UTC by Jarcho

fixes #8290

Ideally this would fix the macro parsing code to handle this, but this is a smaller change and easier to back port.

changelog: Handle implicit named arguments in `useless_format`

2022-01-15 19:36 UTC, rust-highfive commented
r? @giraffate

(rust-highfive has picked a reviewer for you, use r? to override)

2022-01-15 19:54 UTC, xFrednet commented on tests/ui/format.rs
> +    let _ = format!("{x}");
Could you also add a test were the value is format and where a named argument is used, like this :upside_down_face::

```rs
// Formatted (Ignore)
let y = 10;
format!("{y:+}");

// named argument
format!("{x}", x=y)

2022-01-16 12:44 UTC, giraffate requested changes
Can you add the `msrv`? The named arguments was added in 1.58

2022-01-16 13:21 UTC, camsteffen commented
I don't think msrv is needed since we aren't making a code suggestion with the new feature.

I wonder if we could use `path_to_local` and `hir().name(id)`. But this seems to work well enough.

2022-01-16 13:22 UTC, giraffate commented
> Can you add the `msrv`? The named arguments was added in 1.58

Oh, is there a compile error in the first place?

2022-01-16 13:23 UTC, giraffate approved these changes

2022-01-16 13:24 UTC, giraffate commented
@bors r+

Thanks!

2022-01-16 13:41 UTC, merged