New lint `bytes_count_to_len`
rust-lang/rust-clippy pull request #8375
Opened 2022-01-31 00:51 UTC by c-rus

Fixes #8083 

changelog:
• adds new lint ``[`bytes_count_to_len `]`` to consider replacing `.bytes().count()` with `.len()`

2022-01-31 00:51 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @Manishearth (or someone else) soon.

Please see [the contribution instructions](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md) for more information.

2022-02-03 04:19 UTC, Manishearth requested changes
Good start, some suggestions

2022-02-03 04:19 UTC, Manishearth commented on clippy_lints/src/bytes_count_to_len.rs
> +    "Using bytest().count() when len() performs the same functionality"
```suggestion
    "Using bytes().count() when len() performs the same functionality"
```

2022-02-03 04:19 UTC, Manishearth commented on clippy_lints/src/bytes_count_to_len.rs
> +            if count_path.ident.name == rustc_span::sym::count;
We should use `match_def_path` here and below

And we should ensure the type is `str`

2022-03-28 12:55 UTC, giraffate commented
@c-rus ping from triage. Can you have any question to work on this?

2022-04-13 13:06 UTC, closed without merging

2022-04-14 00:34 UTC, kyoto7250 commented
I'm interested in this PR.
Can I take over and create another PR?

2022-04-14 00:53 UTC, giraffate commented
Yes, thanks!

2022-04-16 09:36 UTC, kyoto7250 commented
I opened a PR that took over.

https://github.com/rust-lang/rust-clippy/pull/8711