Extend precedence to lint for masking bits and shifts
rust-lang/rust-clippy pull request #8735
Opened 2022-04-22 21:20 UTC by goth-turtle

Currently this lints for any expression `_ & _ << _` or `_ & _ >> _`, and suggests adding parentheses, like so: `(_ & _) << _`.
Also, im not really sure about my wording with the documentation i added, so id appreciate some feedback on that. Thanks!

changelog: extended [`precedence`] to lint for bitmasking with shifting without parentheses

fixes #6632

2022-04-22 21:20 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @Manishearth (or someone else) soon.

Please see [the contribution instructions](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md) for more information.

2022-04-25 07:38 UTC, Manishearth commented
r? @Jarcho 

(I'm travelling rn and might not be able to do full reviews, can rubber-stamp after you've had a look at it)

2022-04-26 04:13 UTC, Jarcho commented
You'll need to switch the suggestion to `x & (y >> z)`? The precedence lint is meant as a note that the code as written may be easy to misread, not that the code is necessarily wrong.

I'll give a proper review tomorrow.

2022-04-27 03:50 UTC, Jarcho requested changes
Finished an initial read of the changes. The current implementation will lint twice on expression such as `a + b & x >> d`.

I'd also like to see this extended to handle any combination of `&`, `|`, and `^` with either shift operation. The approach would be to change the match expression to `match (op, get_bin_opt(left), get_bin_opt(right))` and then fill in arms like `(BitAnd | BitOr | BitXor, Some(Shl | Shr | Add | ...), Some(Shl | Shr | Add | ...))`. `get_bin_opt` will need to be written as well.

2022-04-27 03:50 UTC, Jarcho commented on clippy_lints/src/precedence.rs
> +        match (is_arith_expr(left), is_arith_expr(right)) {
This is the match expression that would need to change.

2022-05-18 00:21 UTC, giraffate commented
@goth-turtle ping from triage. Can you have any question on this?

2023-10-06 21:50 UTC, blyxyas commented
@goth-turtle closing this it has been inactive for 403 days. Closing this as (from your contribution history) it seems like you're no longer interested in OSS (nothing wrong about that :heart:).

If you return to the community, and are interested in continuing this PR, don't hesitate to reopen this PR (●ↀωↀ●)

2023-10-06 21:50 UTC, closed without merging