[dbg_macro] tolerates use of `dbg!` in items which have `#[cfg(test)]` attribute
rust-lang/rust-clippy pull request #8838
Opened 2022-05-17 15:40 UTC by tamaroning

fix: #8758 
changelog: [dbg_macro] tolerates use of `dbg!` in items which have `#[cfg(test)]` attribute

2022-05-17 15:41 UTC, rust-highfive commented
r? @flip1995

(rust-highfive has picked a reviewer for you, use r? to override)

2022-05-17 20:20 UTC, xFrednet commented
r? @Jarcho

2022-05-18 04:55 UTC, Jarcho requested changes
Overall looks good. Just two little style related nits.

2022-05-19 09:59 UTC, tamaroning commented
@Jarcho 
Thank you for your review. I fixed them.

2022-05-19 10:18 UTC, xFrednet approved these changes
This looks good to me. I'll leave the final r+ to @Jarcho 

@bors delegate @Jarcho

@Jarchen when you merge, it would be cool if you could use `r=Jarcho,xFrednet` :upside_down_face:

2022-05-19 10:19 UTC, xFrednet commented
@bors delegate @Jarcho

(Bors doesn't work in review comments)

2022-05-19 10:21 UTC, xFrednet commented
@bors delegate=Jarcho

(Bors doesn't work in review comments)

2022-05-19 15:46 UTC, Jarcho commented
Everything looks good. @bors r=Jarcho,xFrednet

2022-05-19 16:04 UTC, merged

2022-05-26 09:08 UTC, afetisov commented
That is now a very confusing behaviour on the part of that lint. When I run it, I expect it to find _all_ uses of dbg, regardless of test or no test. When I use dbg in tests, it's also for debugging purposes, and leaving it in will just cause tests to spam debug messages in the console.

A change like that should have been a separate lint with a clear name, which could be separately allowed.

2022-05-26 09:11 UTC, xFrednet commented
I would dislike splitting the lint, but we could introduce a config value, which enables the user to specify the behavior in tests. Do you think that is a better idea? @afetisov

2022-05-26 09:19 UTC, afetisov commented
I don't have any objections to a config value, I would just want the lint to be enabled everywhere by default.

2022-05-26 09:27 UTC, afetisov commented
I think a separate lint is a bit better for discoverability, since Clippy will print its name when it triggers. Config values are afaik mentioned only in the docs. But from a practical perspective, a config value indeed makes more sense.

2022-05-26 09:30 UTC, xFrednet commented
The question would be how the lints, should be split. It wouldn't make sense to have one lint that tests everything and one that is specific to anything but functions, as they would overlap. Therefore, we would need one lint for tests and one for other code. For me, that would be more confusing than a config value. But I'm also used to working with the lint list ^^

2022-05-26 10:36 UTC, tamaroning commented
I think it is better to introduce a config value too. Mentioning it in warning messages of [dbg_macro] might be useful.

2022-05-26 10:55 UTC, xFrednet commented
Would you mind adding it? We have some [documentation](https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md#adding-configuration-to-a-lint) how this can be done. If not, we can just create a new issue :upside_down_face: