Fix typos
rust-lang/rust-clippy pull request #9159
Opened 2022-07-12 16:37 UTC by alex-semenyuk

changelog: none

2022-07-12 16:37 UTC, rust-highfive commented
r? @dswij

(rust-highfive has picked a reviewer for you, use r? to override)

2022-07-12 17:43 UTC, Serial-ATA requested changes

2022-07-12 17:43 UTC, Serial-ATA commented on clippy_lints/src/functions/mod.rs
> +    /// code may opt to (miss)use it as a basic two-variant-enum. In that case,
```suggestion
    /// code may opt to (mis)use it as a basic two-variant-enum. In that case,
```

2022-07-12 17:43 UTC, Serial-ATA commented on clippy_lints/src/serde_api.rs
> +    /// Checks for miss-uses of the serde API.
```suggestion
    /// Checks for mis-uses of the serde API.
```

2022-07-13 09:58 UTC, dswij requested changes
Thanks, just a small typo and it's good to merge

2022-07-13 09:58 UTC, dswij commented on clippy_lints/src/loops/manual_find.rs
> +        // This should be the funcition body
```suggestion
        // This should be the function body
```

2022-07-13 12:51 UTC, alex-semenyuk commented
Done

2022-07-13 14:42 UTC, dswij commented
@bors r+ squash

Thanks!

2022-07-13 18:03 UTC, dswij commented
The PR is merged in master, but it seems like squashing with bors is not closing the issue correctly at the moment.

I will be manually closing this one.

2022-07-13 18:03 UTC, closed without merging