fallout: allow new uninlined_format_args in tests
rust-lang/rust-clippy pull request #9547
Opened 2022-09-27 23:19 UTC by nyurik

In order to switch `clippy::uninlined_format_args` from pedantic to style, all existing tests must not raise a warning. I did not want to change the actual tests, so this is a relatively minor change that:

* add `#![allow(clippy::uninlined_format_args)]` where needed
* normalizes all allow/deny/warn attributes
   * all allow attributes are grouped together
   * sorted alphabetically
   * the `clippy::*` attributes are listed separate from the other ones.
   * deny and warn attributes are listed before the allowed ones

* minor spelling rename - "moveable" -> "movable"

See also https://github.com/rust-lang/rust-clippy/pull/9233, https://github.com/rust-lang/rust-clippy/pull/9525, https://github.com/rust-lang/rust-clippy/pull/9527

cc: @llogiq @Alexendoo

changelog: none

2022-09-27 23:19 UTC, rust-highfive commented
r? @flip1995

(rust-highfive has picked a reviewer for you, use r? to override)

2022-09-30 09:55 UTC, flip1995 requested changes
This adds an allow attribute for the `uninlined_format_args` lint for **every** test file, even if it doesn't even use the `format!` macro. This is highly unnecessary and not something we want. Please only add this attribute to the tests that would actually fail due to the new lint.

2022-10-01 01:29 UTC, nyurik commented
> This adds an allow attribute for the `uninlined_format_args` lint for **every** test file, even if it doesn't even use the `format!` macro. This is highly unnecessary and not something we want. Please only add this attribute to the tests that would actually fail due to the new lint.

@flip1995 that is not correct - there are 801 test .rs files in the `tests/ui` dir, and I only changed 86 of them - only about 10%, all of which are required. I reevaluated all of them again, and did find one -- `tests/ui/empty_line_after_outer_attribute.rs` that I refactored by accident (reverted).  Just to keep things focused, I also undeed the `moveable -> movable` rename.  What's left are all needed.

2022-10-04 02:28 UTC, nyurik commented
@flip1995 is there still something that needs to be done to this PR? Thx!

2022-10-04 07:20 UTC, flip1995 approved these changes
Sorry, I was away over the weekend (long weekend in Germany).

All good now. Maybe I saw ghosts, but I thought I saw a file where it wasn't necessary. Thanks for addressing this!

2022-10-04 07:20 UTC, flip1995 commented
@bors r+ p=10

2022-10-04 07:36 UTC, merged