add [`permissions_set_readonly_false`] #9702
rust-lang/rust-clippy pull request #9744
Opened 2022-10-28 20:14 UTC by dboso

changelog: add new lint `permissions_set_readonly_false` #9702

2022-10-28 20:14 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @Jarcho (or someone else) soon.

Please see [the contribution instructions](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md) for more information.

2022-10-29 01:28 UTC, Jarcho requested changes
Just a couple of small style nits.

Not 100% sure about `suspicious`, but I don't think any of the other categories fit and the behaviour on unix is pretty bad.

2022-10-29 01:28 UTC, Jarcho commented on clippy_lints/src/permissions_set_readonly_false.rs
> +        if let ExprKind::MethodCall(path, receiver, args, _) = &expr.kind {
`args` should be `[arg]`.

2022-10-29 01:28 UTC, Jarcho commented on clippy_lints/src/permissions_set_readonly_false.rs
> +            if_chain! {
Let-chains should be used here rather than `if_chain`. e.g.
```rust
if let Some(x) = foo
    && let y = bar
    && baz
{}
```

2022-10-31 00:39 UTC, Jarcho requested changes
Another small style nit. You can squash the changes and keep everything as one commit.

2022-10-31 00:39 UTC, Jarcho commented on clippy_lints/src/permissions_set_readonly_false.rs
> +                && [arg].len() == 1
There's no reason to use `[arg]` here. You're creating a type `[&Expr; 1]` which will always have a length of one.

Next line also has the same unneeded array creation. Can just be `&arg.kind`.

2022-11-20 22:53 UTC, Jarcho commented
Ping @dboso. Do you plan on continuing this?

2022-11-22 07:05 UTC, dboso commented
Feel free to take over :)

Sent from Proton Mail mobile

-------- Original Message --------
On 20 Nov 2022, 23.53, Jason Newcomb wrote:

> Ping ***@***.***(https://github.com/dboso). Do you plan on continuing this?
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/rust-lang/rust-clippy/pull/9744#issuecomment-1321265889), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AMVHJVJDTMVBT4DDCYRZ7VDWJKTWTANCNFSM6AAAAAARRMMSZM).
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-12-11 15:42 UTC, chansuke commented
I'd like to take over this PR

2022-12-14 21:51 UTC, xFrednet commented
I'm closing this in favor of #10063

Thank you for the groundwork @dboso. If the new PR stalls, and you want to continue this work feel free to reopen it or create a new one :)

2022-12-14 21:51 UTC, closed without merging